#!/bin/sh
# Bundle sakshi into a single dist/sakshi.cyr for external consumers.
# Usage: sh scripts/bundle.sh
# Output: dist/sakshi.cyr — single-file equivalent of src/lib.cyr.
#
# Internal consumers (Cyrius stdlib, sibling AGNOS crates) should prefer
# `include "src/lib.cyr"` against a sibling checkout; the bundle exists
# for crates that pull sakshi via `[deps.sakshi] modules = [...]`.

set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION=$(cat "$ROOT/VERSION" | tr -d '[:space:]')

mkdir -p "$ROOT/dist"

# Concatenation order must match src/lib.cyr include order:
# format (primitives) → output (uses format) → error → trace → span
MODULES="src/format.cyr src/output.cyr src/error.cyr src/trace.cyr src/span.cyr"

{
echo "# sakshi.cyr — tracing, error handling, and structured logging for Cyrius"
echo "# Bundled distribution of sakshi v${VERSION}"
echo "# Source: https://github.com/MacCracken/sakshi"
echo "# License: GPL-3.0-only"
echo "#"
echo "# Usage: include \"lib/sakshi.cyr\" (external) or \"src/lib.cyr\" (sibling checkout)"
echo "#"
echo "# Single-file distribution. Zero heap allocation."
echo "# Generated by scripts/bundle.sh — do not edit by hand."
echo "#"
echo "# External consumers using sakshi_set_emit_hook MUST also include"
echo "# lib/fnptr.cyr before this file (the bundle strips its own includes)."
echo "#"
echo "# Constraints:"
echo "#   - Single-threaded only. No synchronization on global state."
echo "#   - UDP output is unencrypted and unauthenticated."
echo "#   - Monotonic timestamps overflow i64 after ~292 years of uptime."

for f in $MODULES; do
    echo ""
    echo "# --- $(basename "$f") ---"
    echo ""
    grep -v "^include " "$ROOT/$f"
done

# cat -s squeezes runs of blank lines (left behind by stripped `include`
# lines) down to a single blank. Keeps `cyrlint` happy without editing
# source headers to hide the gap.
} | cat -s > "$ROOT/dist/sakshi.cyr"

echo "dist/sakshi.cyr: $(wc -l < "$ROOT/dist/sakshi.cyr") lines (v${VERSION})"
